#!/usr/bin/env python3
"""Interactive setup for Neon PostgreSQL connection."""
import os
from pathlib import Path

def setup_neon():
    repo_root = Path(__file__).resolve().parent.parent
    env_file = repo_root / ".env"

    print("\n" + "="*70)
    print("GARAGE - Neon PostgreSQL Setup")
    print("="*70)

    db_url = input("\nPaste your Neon DATABASE_URL (from Neon dashboard):\n> ").strip()

    if not db_url.startswith("postgresql://"):
        print("[ERROR] Invalid URL format. Must start with 'postgresql://'")
        return False

    jwt_secret = input("\nEnter JWT_SECRET_KEY (leave blank for dev auto-generate):\n> ").strip()
    if not jwt_secret:
        jwt_secret = "dev-auto-generated"

    admin_email = input("\nEnter ADMIN_EMAIL (default: admin@garage.local):\n> ").strip()
    if not admin_email:
        admin_email = "admin@garage.local"

    env_content = f"""# GARAGE Environment Configuration
# Generated by setup script - Keep secure!

JWT_SECRET_KEY={jwt_secret}
DATABASE_URL={db_url}
ADMIN_EMAIL={admin_email}
ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000
ENV=development
"""

    env_file.write_text(env_content)
    print(f"\n[SUCCESS] Created {env_file}")
    print(f"[INFO] Next: python scripts/test_db_connection.py")
    return True


if __name__ == "__main__":
    try:
        setup_neon()
    except KeyboardInterrupt:
        print("\n[CANCEL] Setup cancelled.")
        exit(1)
